export const products = [
    {
        id: 1,
        title:"Realme earbuds Wireless Fingerprint Bluetooth",
        slug: "Realme earbuds Wireless",
        img: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8ZWFyYnVkc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
        price: 500,
        company: "Nike",
        rating: 4.5,
        numReviews: 10,
        info: "Although the radiation caused by the mobile phone is negligible, it is tiring to hold the mobile phone to answer the call for a long time. Using a Bluetooth headset can not only prevent the mobile phone from radiation but also facilitate the answering of the call. Reducing mobile phone radiation can also be said to be a more obvious advantage of Blueto",
        inCart: false,
        countInStock: 0,
        category: "earbuds"
    },
    {
        id: 2,
        title:"Earbuds Bluetooth Headsets Bluetooth Earbuds",
        slug: "Earbuds Bluetooth Headsets",
        img: "https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8ZWFyYnVkc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
        price: 600,
        company: "Nike",
        rating: 2,
        numReviews: 6,
        info: "The Bluetooth headset has been placed for a long time. If not used for a long time, the lithium battery inside the headset will be in the state. As long as the charging time is more than 30 minutes, the headset will show the charging status. 2.",
        inCart: false,
        countInStock: 6,
        category: "earbuds"
    },
    {
        id: 3,
        title:"Edifier X2 TWS Earbuds Wireless Earphones",
        slug: "Edifier X2 TWS Earbuds Wireless Earphones",
        img: "https://media.istockphoto.com/id/1346147559/photo/modern-wireless-bluetooth-headphones-with-charging-case-on-a-blue-background.jpg?b=1&s=170667a&w=0&k=20&c=BYU1Hus6DkSaivEEZ5xLGschmpFr1j-M-IPfjYoJQ7s=",
        price: 1000,
        company: "Nike",
        rating: 4.5,
        numReviews: 10,
        info: "13mm large driver ensures a wide soundstage and balanced sound. The bass is solid and powerful with exhilarating details, offering you a live music experience.",
        inCart: false,
        countInStock: 6,
        category: "earbuds"
    },
    {
        id: 4,
        title:"2023 Earbuds Wireless Earphones",
        slug: "2023 Earbuds Wireless Earphones",
        img: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8ZWFyYnVkc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
        price: 900,
        company: "Nike",
        rating: 4.5,
        numReviews: 10,
        info: "13mm large driver ensures a wide soundstage and balanced sound. The bass is solid and powerful with exhilarating details, offering you a live music experience.",
        inCart: false,
        countInStock: 6,
        category: "earbuds"
    },
    {
        id: 5,
        title:"8570 Bluetooth Headphones",
        slug:"8570 Bluetooth Headphones",
        img: "https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/50/8514051/1.jpg?8744",
        price: 900,
        company: "Nike",
        rating: 4.5,
        numReviews: 10,
        info: "Bluetooth 4.0+EDR & CSR Chipset: These headphones feature the international Bluetooth 4.0 CSR chipset, it can create HD audio and a wide frequency response from 20Hz to 20kHz, low power consumption, superior compatibility (Mobile Phones, Tablet PCs, Notebooks; all Bluetooth enabled devices & a 3.5mm audio jack).",
        inCart: false,
        countInStock: 6,
        category: "headphones"
    },
    {
        id: 6,
        title:"Foldable Bluetooth Headphones",
        slug:"Foldable Bluetooth Headphones",
        img: "https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/25/6839302/1.jpg?2952",
        price: 900,
        company: "Nike",
        rating: 4.5,
        numReviews: 10,
        info: "Bluetooth 4.0+EDR & CSR Chipset: These headphones feature the international Bluetooth 4.0 CSR chipset, it can create HD audio and a wide frequency response from 20Hz to 20kHz, low power consumption, superior compatibility (Mobile Phones, Tablet PCs, Notebooks; all Bluetooth enabled devices & a 3.5mm audio jack).",
        inCart: false,
        countInStock: 6,
        category: "headphones"
    },
    {
        id: 7,
        title:"2023 Foldable Bluetooth Headphones",
        slug:"2023 Foldable Bluetooth Headphones",
        img: "https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/54/6839302/1.jpg?3008",
        price: 900,
        company: "Nike",
        rating: 4.5,
        numReviews: 10,
        info: "Bluetooth 4.0+EDR & CSR Chipset: These headphones feature the international Bluetooth 4.0 CSR chipset, it can create HD audio and a wide frequency response from 20Hz to 20kHz, low power consumption, superior compatibility (Mobile Phones, Tablet PCs, Notebooks; all Bluetooth enabled devices & a 3.5mm audio jack).",
        inCart: false,
        countInStock: 6,
        category: "headphones"
    },
    {
        id: 8,
        title:"Foldable Bluetooth Headphones/Earphone",
        slug:"Foldable Bluetooth Headphones/Earphone",
        img: "https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/65/3923361/1.jpg?4754",
        price: 900,
        company: "Nike",
        rating: 4.5,
        numReviews: 10,
        info: "Bluetooth 4.0+EDR & CSR Chipset: These headphones feature the international Bluetooth 4.0 CSR chipset, it can create HD audio and a wide frequency response from 20Hz to 20kHz, low power consumption, superior compatibility (Mobile Phones, Tablet PCs, Notebooks; all Bluetooth enabled devices & a 3.5mm audio jack).",
        inCart: false,
        countInStock: 6,
        category: "headphones"
    },
    {
        id: 9,
        title:"Full Tourch Screen Smart Watch",
        slug:"Full Tourch Screen Smart Watch",
        img: "https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/67/7454491/1.jpg?2677",
        price: 2000,
        company: "Nike",
        rating: 4.5,
        numReviews: 10,
        info: "Bluetooth 4.0+EDR & CSR Chipset: These headphones feature the international Bluetooth 4.0 CSR chipset, it can create HD audio and a wide frequency response from 20Hz to 20kHz, low power consumption, superior compatibility (Mobile Phones, Tablet PCs, Notebooks; all Bluetooth enabled devices & a 3.5mm audio jack).",
        inCart: false,
        countInStock: 6,
        category: "watch"
    },
    {
        id: 10,
        title:"Full Tourch Screen Smart Watch For Android and IOS",
        slug:"Full Tourch Screen Smart Watch",
        img: "https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/60/796239/1.jpg?4478",
        price: 2000,
        company: "Nike",
        rating: 4.5,
        numReviews: 10,
        info: "Bluetooth 4.0+EDR & CSR Chipset: These headphones feature the international Bluetooth 4.0 CSR chipset, it can create HD audio and a wide frequency response from 20Hz to 20kHz, low power consumption, superior compatibility (Mobile Phones, Tablet PCs, Notebooks; all Bluetooth enabled devices & a 3.5mm audio jack).",
        inCart: false,
        countInStock: 6,
        category: "watch"
    },
    {
        id: 11,
        title:"IOS Smart Watch Full Tourch Screen",
        slug:"IOS Smart Watch Full Tourch Screen",
        img: "https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/32/7839291/1.jpg?5220",
        price: 2000,
        company: "Nike",
        rating: 4.5,
        numReviews: 10,
        info: "Bluetooth 4.0+EDR & CSR Chipset: These headphones feature the international Bluetooth 4.0 CSR chipset, it can create HD audio and a wide frequency response from 20Hz to 20kHz, low power consumption, superior compatibility (Mobile Phones, Tablet PCs, Notebooks; all Bluetooth enabled devices & a 3.5mm audio jack).",
        inCart: false,
        countInStock: 6,
        category: "watch"
    },
    {
        id: 12,
        title:"IOS Smart Watch Full Tourch Screen",
        slug:"IOS Smart Watch Full Tourch Screen",
        img: "https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/01/8454491/1.jpg?2678",
        price: 2000,
        company: "Nike",
        rating: 4.5,
        numReviews: 10,
        info: "Bluetooth 4.0+EDR & CSR Chipset: These headphones feature the international Bluetooth 4.0 CSR chipset, it can create HD audio and a wide frequency response from 20Hz to 20kHz, low power consumption, superior compatibility (Mobile Phones, Tablet PCs, Notebooks; all Bluetooth enabled devices & a 3.5mm audio jack).",
        inCart: false,
        countInStock: 6,
        category: "watch"
    },
    {
        id: 13,
        title:"New iphone X,11,12,and 13 pro max ",
        slug:"New iphone X",
        img: "https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/37/8976501/1.jpg?6296",
        price: 2000,
        company: "Nike",
        rating: 4.5,
        numReviews: 10,
        info: "Bluetooth 4.0+EDR & CSR Chipset: These headphones feature the international Bluetooth 4.0 CSR chipset, it can create HD audio and a wide frequency response from 20Hz to 20kHz, low power consumption, superior compatibility (Mobile Phones, Tablet PCs, Notebooks; all Bluetooth enabled devices & a 3.5mm audio jack).",
        inCart: false,
        countInStock: 6,
        category: "Apple"
    },
    {
        id: 14,
        title:"Apple Iphone 12 x3 max 64gb space ",
        slug:"Apple Iphone 12",
        img: "https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/71/3525221/1.jpg?2128",
        price: 2000,
        company: "Nike",
        rating: 4.5,
        numReviews: 10,
        info: "Bluetooth 4.0+EDR & CSR Chipset: These headphones feature the international Bluetooth 4.0 CSR chipset, it can create HD audio and a wide frequency response from 20Hz to 20kHz, low power consumption, superior compatibility (Mobile Phones, Tablet PCs, Notebooks; all Bluetooth enabled devices & a 3.5mm audio jack).",
        inCart: false,
        countInStock: 6,
        category: "Apple"
    },
]